name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Verify Go toolchain
        run: go version
      - name: Tidy and vet
        run: |
          go mod tidy
          go vet ./...
      - name: Test
        run: go test ./...
      - name: Build (Windows)
        run: go build -trimpath -ldflags "-s -w" -o dist/wsl2-port-forwarder.exe .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: wsl2-port-forwarder.exe
          path: dist/wsl2-port-forwarder.exe

  gitleaks:
    name: Secret scan (gitleaks)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: --redact --verbose
